### ISSUE TITLE
ImportError: cannot import name 'DoNothingDataCollator' from 'overrides'

### ISSUE THREAD

**Issue by smitkadvani** [steqe/steqe#1]
I am trying to reproduce the code, while doing so I came across I`mportError: cannot import name 'DoNothingDataCollator' from 'overrides'`
I have downloaded `pip install overrides` but didnt resolve the error. 
Later, I have checked every versions of overrides package and didnt' find DoNothingDataCollator.

**Comment by Slash0BZ** [comment]
It seems there is a missing file, and I have uploaded that file called `overrides.py`. Please let me know if this solves the issue. 

Ben

**Comment by smitkadvani** [comment]
Thank you Ben.
It works.

**Comment by smitkadvani** [comment]
Thank you Ben for quick response.
Issue is resolved and I’ve closed issue on GitHub.

Regards,
Smit
