### ISSUE TITLE
not able to load pre-trained model.

### ISSUE THREAD

**Issue by smitkadvani** [steqe/steqe#2]
After training model using train.py file,
I got output stored in output directory.

Later when I try to load_model for independent prediction, I got following size mismatch error.
It would be great if you can help me resolving this error. 

`RuntimeError: Error(s) in loading state_dict for T5ForConditionalGeneration:
        size mismatch for shared.weight: copying a param with shape torch.Size([32100, 1024]) from checkpoint, the shape in current model is torch.Size([32128, 1024]).
        size mismatch for encoder.embed_tokens.weight: copying a param with shape torch.Size([32100, 1024]) from checkpoint, the shape in current model is torch.Size([32128, 1024]).
        size mismatch for decoder.embed_tokens.weight: copying a param with shape torch.Size([32100, 1024]) from checkpoint, the shape in current model is torch.Size([32128, 1024]).
        size mismatch for lm_head.weight: copying a param with shape torch.Size([32100, 1024]) from checkpoint, the shape in current model is torch.Size([32128, 1024]).`

**Comment by Slash0BZ** [comment]
how did you load the model?

**Comment by smitkadvani** [comment]
Thank you for your super-fast response. 
I have used following code to load model.
`config = AutoConfig.from_pretrained("t5-large")
#config = AutoConfig.from_pretrained("t5-small")
model = T5ForConditionalGeneration(config=config)
model.load_state_dict(torch.load('spatial_covid_seed10/pytorch_model.bin'))
`

**Comment by Slash0BZ** [comment]
Can you try model = T5ForConditionalGeneration.from_pretrained(PATH)? load_state_dict will not work because transformers performs some additional operations such as aligning the vocab size

**Comment by smitkadvani** [comment]
It's working.
