### ISSUE TITLE
Error while generating evaluation 

### ISSUE THREAD

**Issue by smitkadvani** [steqe/steqe#3]
```
Prediction:   0%|                                                                                                                       | 0/32 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "temp_Evaluate.py", line 342, in <module>
    main()
  File "temp_Evaluate.py", line 308, in main
    inputs[k] = v.cuda()
AttributeError: 'list' object has no attribute 'cuda'
```

Once model is trained, while evaluation I got this error.
`for inputs in tqdm(data_loader, "Prediction"):
            for k, v in inputs.items():
                inputs[k] = v.cuda() #Line 2
.
.
.
` 

Later, I googled it and changed Line 2 with following code 
`for inputs in tqdm(data_loader, "Prediction"):
            for k, v in inputs.items():
                #inputs[k] = v.cuda()
                inputs[k] = torch.cat(v).cuda()`
But it didn't solve error.

**Comment by Slash0BZ** [comment]
Is this from the code that we provided or something you wrote?

**Comment by smitkadvani** [comment]
From the code, provided by you.
https://github.com/steqe/steqe/blob/main/experiment/train_t5.py#L305

**Comment by Slash0BZ** [comment]
This line, yes, I am aware. My question is that if you run our train.py exactly in the evaluation mode, will you also get this error? You have to use the exact same data loader and everything else for this line to work because inputs[k] can be anything if you are using custom loaders.

**Comment by smitkadvani** [comment]
I'm using exactly same. Initially, I realized that i was using different transformers version but after changing it to you transformers=2.11.0,
I get different error 

> 

> `Traceback (most recent call last):
  File "temp_Evaluate.py", line 344, in <module>
    main()
  File "temp_Evaluate.py", line 308, in main
    inputs[k] = v.cuda()
AttributeError: 'list' object has no attribute 'cuda'`

Then I have modified line
https://github.com/steqe/steqe/blob/main/experiment/train_t5.py#L305
by 
`inputs[k] = torch.cat(v).cuda()`.
I get his error 
`  File "temp_Evaluate.py", line 344, in <module>
    main()
  File "temp_Evaluate.py", line 319, in main
    forced_eos_token_id=1,
  File "/nas/home/skadvani/anaconda3/envs/protoqa/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "/nas/home/skadvani/anaconda3/envs/protoqa/lib/python3.6/site-packages/transformers/modeling_utils.py", line 997, in generate
    ), "If input_ids is not defined, `bos_token_id` should be a positive integer."
AssertionError: If input_ids is not defined, `bos_token_id` should be a positive integer.`

**Comment by Slash0BZ** [comment]
My guess is that you missed some steps compared to our provided code. In our train.py, inputs are a dictionary of {key:tensor}, which is guaranteed by the DoNothingDataCollator. Then, v should be the tensor in that dict, which is NOT a list, and can perform .cuda(). Can you check your code and see why v is a list in your code?

**Comment by smitkadvani** [comment]
I realized, I had commented some portion of code. I am really sorry for bothering you.
